name: Test Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Test build output
        run: |
          echo "Build completed successfully!"
          echo "Checking dist folder contents:"
          ls -la dist/
          echo "Checking dist/assets folder:"
          ls -la dist/assets/
          echo "Build size:"
          du -sh dist/